### ISSUE TITLE
Please provide binaries for download

### ISSUE THREAD

**Issue by probonopd** [MartinPulec/UltraGrid-build-scripts#1]
https://github.com/MartinPulec/UltraGrid-build-scripts/blob/ff9ccad951e96df801a00066113f87d3b37639ce/Linux/ultragrid-nightly-build-release.sh#L23

Can you please provide binaries for download, e.g., on GitHub Releases? Thanks.

**Comment by MartinPulec** [comment]
Actually this scripts are used to build [the binaries here](https://github.com/CESNET/UltraGrid/releases). It is just in separate repo because I thought it is better for deployment (the scripts clone actual main repo).

**Comment by probonopd** [comment]
Thank you very much. I wasn't aware of that. Thanks for providing an AppImage.

**Comment by MartinPulec** [comment]
Yeah, thanks a lot also for developing AppImage, it is a great distribution format. We may eventually use OBS for the build when a colleague configures the target. We will see whether it is better.
